name: Publish NPM
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: revolist/revogrid-actions
          ref: main
          path: ./actions
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Release grid new version
        uses: ./actions/release-grid
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
      