name: Publish NPM
on:
  release:
    types: [created]
permissions: write-all
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: revolist/revogrid-actions
          ref: main
          path: ./actions
          token: ${{ secrets.REPO_TOKEN }}
      - name: Release grid new version
        uses: ./actions/release-grid
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: ${{ secrets.REPO_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
      