name: Publish NPM
on:
  release:
    types: [created]
permissions: write-all
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: revolist/revogrid-actions
          ref: main
          path: ./actions
          token: ${{ secrets.REPO_TOKEN }}
      - name: Release grid new version
        uses: ./actions/release-grid
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
  update_submodules:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for private submodules
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v4
        with:
          repository: revolist/revogrid-actions
          ref: main
          path: ./actions
          token: ${{ secrets.REPO_TOKEN }}
      - name: Update submodules
        uses: ./actions/update-submodules
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: ${{ secrets.REPO_TOKEN }}
      