name: Publish NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup to publish to npm Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/checkout@v4
      
      # Checout submodule
      - name: Checkout submodules
        run: git submodule update --init --remote --recursive

      - run: npm ci

      # Build
      - run: npm run build
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@revolist'

      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Get version from package.json
      - name: Get version from package.json
        id: version
        run: echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"

        # Update packages with new version
      - run: npm run package:update  -- --version ${{ steps.version.outputs.VERSION }}